### ISSUE TITLE
Project Update

### ISSUE THREAD

**Issue by brianthomkelly** [johncarpenter/Android-GPX-Mock-Location-Provider#3]
Hi John,

I've updated your project to use gradle and added the ability to set the replay delay between GPS points.

It would be great to merge this work back into your core project. Would you consider a pull request on this? It will modify your directory structure totally but the core project is still there.

Brian

**Comment by johncarpenter** [comment]
Absolutely, I haven't taken a look at the project in a while so anyone willing to push something up would be greatly appreciated.

**Comment by brianthomkelly** [comment]
Just closing this ticket off John. Thanks for merging that work in - its a good utility you developed and good to keep it alive.
